export const BREATHING_SOUNDS_CONSTANTS = {
  CATEGORIES: {
    RAIN: 'lluvia',
    OCEAN: 'olas',
    WIND: 'viento',
    FIRE: 'fuego',
    BIRDS: 'pajaros',
  },

  DEFAULT_SOUNDS: [
    {
      _id: 'rain-001',
      nombre: 'Lluvia Suave',
      descripcion: 'Sonido de lluvia ligera en la naturaleza',
      freesound_id: 725603,
      preview_url: 'https://cdn.freesound.org/previews/725/725603_15753134-lq.mp3',
      categoria: 'lluvia',
      duracion_segundos: 300,
      es_activo: true,
    },
    {
      _id: 'ocean-001',
      nombre: 'Olas del Mar',
      descripcion: 'Sonido de olas relajantes en la playa',
      freesound_id: 827530,
      preview_url: 'https://cdn.freesound.org/previews/827/827530_2718606-lq.mp3',
      categoria: 'olas',
      duracion_segundos: 300,
      es_activo: true,
    },
    {
      _id: 'wind-001',
      nombre: 'Viento en Bosque',
      descripcion: 'Sonido de viento suave entre árboles',
      freesound_id: 621009,
      preview_url: 'https://cdn.freesound.org/previews/621/621009_13074022-lq.mp3',
      categoria: 'viento',
      duracion_segundos: 300,
      es_activo: true,
    },
    {
      _id: 'fire-001',
      nombre: 'Fuego Crepitante',
      descripcion: 'Sonido de fuego acogedor',
      freesound_id: 563764,
      preview_url: 'https://cdn.freesound.org/previews/563/563764_6253486-lq.mp3',
      categoria: 'fuego',
      duracion_segundos: 300,
      es_activo: true,
    },
    {
      _id: 'birds-001',
      nombre: 'Canto de Pájaros',
      descripcion: 'Sonido de pájaros en la naturaleza',
      freesound_id: 327447,
      preview_url: 'https://cdn.freesound.org/previews/327/327447_4028726-lq.mp3',
      categoria: 'pajaros',
      duracion_segundos: 300,
      es_activo: true,
    },
  ],
};